### ISSUE TITLE
Formatting not preserved after copy-paste

### ISSUE THREAD

**Issue by kurpav00** [allemand-instable/Colorful-Comments#15]
When copy-pasting source code from VS Code to another app, like MS Word, the color formatting of the comments is not preserved and reverts to the original VS Code color scheme. So for example this
![image](https://github.com/user-attachments/assets/6d25d5fe-c96d-4095-82a4-fd3c54770239)
turns into this when pasted
![image](https://github.com/user-attachments/assets/8460f0de-93a5-4268-a9dc-e69d06afcbe3)
This issue impacts workflows that involve sharing code snippets with specific formatting, such as documentation, presentations, or reports where consistency in color formatting is essential. It would be helpful if the color formatting could be preserved accurately in copy-pasting operations.

**Comment by code-instable** [comment]
Hello, this is because the coloring part is not encoded within the string itself, but rather a style applied to the view (you can view it like a webpage — which is exactly what VSCODE editor views are)

This is basically a "CSS stuff" applied afterward, and therefore only affect the editor view and not the content, I don't know if there is a way to make it copiable tbh without making the whole thing much clunkier

**Comment by kurpav00** [comment]
> Hello, this is because the coloring part is not encoded within the string itself, but rather a style applied to the view (you can view it like a webpage — which is exactly what VSCODE editor views are)
> 
> This is basically a "CSS stuff" applied afterward, and therefore only affect the editor view and not the content, I don't know if there is a way to make it copiable tbh without making the whole thing much clunkier

OK, thank you anyway for the explanation.
