### ISSUE TITLE
[Feature Request] Additional extension customisation that is accessible from within VScode

### ISSUE THREAD

**Issue by magic-spearmint** [allemand-instable/Colorful-Comments#5]
In a nutshell: Implement one or more additional settings that are accessible from within VSCode for QoL purposes.

To try and help explain what I'm proposing, here's a mock example of what a user could place in VSCode's `settings.json`:
```jsonc
"colorful-comments-refreshed.languageConfig": {
   "ada": {
      "commentFormat": "--" // Valid data types for commentFormat are string and array. If it's a string, then
   },                       // that string is treated as the language's delimiter.
   "go": {
      "commentFormat": [ "//", "/*", "*/" ] // Otherwise, if it's an array, then it must contain three string
   },                                       // elements. These three strings are treated as...
   "lua": {
      "commentFormat": [
         "--",   // ...the delimiter...
         "--[[", // ...the declarator for multi-line comments...
         "]]"    // ...and the terminator for multi-line comments.
      ],
      "tags": [ // This functions exactly like colorful-comments-refreshed.tags, but on a per-language basis
         {      // rather than for all languages.
            "tag": "FIXME",
            "color": "#131917",
            "strikethrough": false,
            "backgroundColor": "#C0FFEE"
         }
      ]
   },
   "python": {
      "commentFormat": [ "#", "\\#\\#\\#", "\\#\\#\\#\\#" ],
      "ignoreFirstLine": true // By default, this is false for all languages unless it's explicitly enabled
   }                          // for them (like here).
}
```

**Comment by code-instable** [comment]
Basically, you would like to add language support directly from the VS-Code user settings.json instead of the extension level, if I get your feature request correctly ?

**Comment by magic-spearmint** [comment]
That's correct. It would also allow for languages already defined within the extension itself to be overridden/customised.

**Comment by code-instable** [comment]
This is an interesting way of handling it 🙂

However, I forked the extension and made appropriate changes to make sure to be able to implement new languages as fast as possible ( with easy to use YAML and "compilation to typescript" using a python script ) so that people can really easily contribute without any hassle to the extension.

I even provided detailed explanations on how to do so in the README, so you don't even have to dive in the code to understand how it works

The idea is to make contributions available to anyone with frequent extension updates, that kind of feature would incentivize people to keep additions for themselves, I'm not so sure about that route 🤔

**Comment by code-instable** [comment]
Maybe if I only allow to customize already implemented languages ( the override part ), it would be still be compatible with the philosophy of the fork, and I hope you do agree with the arguments I provided 🙂
