### ISSUE TITLE
LANGUAGE SUPPORT for Jupyter Notebooks '.ipynb'

### ISSUE THREAD

**Issue by lundeen-bryan** [allemand-instable/Colorful-Comments#7]
Love this but is there a way to make it work in a Jupyter notebook with multiline comments? If so please explain, if not, can it be added as a feature please? I would really appreciate it because otherwise I love this extension!

**Comment by code-instable** [comment]
I will definitely have a look into it, as I myself use notebooks quite a lot, thanks for the input 🙂

**Comment by code-instable** [comment]
A jupyter notebook is basically a json
Therefore you can see that a multiline comment here is a `\"\"\"` string instead of `"""`

That might be the reason why but I am not sure

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "test()\n",
    "\n",
    "# sup bois\n",
    "# sup bois\n",
    "# ~ a\n",
    "\n",
    "\n",
    "\"\"\"\n",
    "~ a\n",
    "\"\"\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "latest",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

I will investigate if there is a simple fix, I have to take into account the fact that jupyter notebook is not only for python but also can deal with other languages such as R, shellscript, .........

SO might be not as straightforward

**Comment by code-instable** [comment]
Seems to be working fine on my own testing, closing the issue
